-- SELECT TITLE, COUNT(RATING)FROM FILM
-- GROUP BY TITLE ;

-- SELECT REPLACEMENT_COST FROM FILM
-- GROUP BY REPLACEMENT_COST;

-- SELECT STORE_ID,COUNT(CUSTOMER_ID) FROM CUSTOMER
-- GROUP BY STORE_ID;

-- SELECT CITY_ID, COUNT(COUNTRY_ID) FROM CITY
-- GROUP BY CITY_ID;

